-- 
-- INITIAL SCHEMA LOAD
-- 
CREATE SCHEMA IF NOT EXISTS FREERIDER_DB;
USE FREERIDER_DB;

DROP TABLE if exists RESERVATION;
DROP TABLE if exists VEHICLE;
DROP TABLE if exists CUSTOMER;

CREATE TABLE if not exists CUSTOMER (
  -- ID INT GENERATED BY DEFAULT AS IDENTITY, -- MySQL does not support IDENTITY
  ID BIGINT AUTO_INCREMENT not null,            -- use AUTO_INCREMENT instead
  NAME VARCHAR(60) not null,
  FIRSTNAME VARCHAR(60) default null,
  CONTACT VARCHAR(60) default null,
  STATUS enum('Active', 'InRegistration', 'Terminated') default null,
  STATUS_CHANGE TIMESTAMP default null,
  -- 
  PRIMARY KEY (ID)
);

CREATE TABLE if not exists VEHICLE (
  -- ID INT GENERATED BY DEFAULT AS IDENTITY,
  ID BIGINT AUTO_INCREMENT not null,
  MAKE VARCHAR(60) not null,
  MODEL VARCHAR(60) not null,
  SEATS INT not null,
  CATEGORY enum('Sedan', 'SUV', 'Convertible', 'Van', 'Bike') not null,
  POWER enum('Gasoline', 'Diesel', 'Electric', 'Hybrid', 'Hydrogen') default null,
  STATUS enum('Active', 'Serviced', 'Terminated') not null,
  PRIMARY KEY (ID)
);

CREATE TABLE if not exists RESERVATION (
  -- ID INT GENERATED BY DEFAULT AS IDENTITY,
  ID BIGINT AUTO_INCREMENT not null,
  CUSTOMER_ID BIGINT not null,
  VEHICLE_ID BIGINT not null,
  TIME_BEGIN TIMESTAMP not null,
  TIME_END TIMESTAMP not null,
  PICKUP VARCHAR(48) not null,
  DROPOFF VARCHAR(48) not null,
  STATUS enum('Inquired', 'InquiryConfirmed', 'Booked', 'Cancelled') not null,
  PRIMARY KEY (ID),
  CONSTRAINT CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) references CUSTOMER (ID),
  CONSTRAINT VEHICLE_ID FOREIGN KEY (VEHICLE_ID) references VEHICLE (ID)
);
